name: FFmpeg library

on:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/ffmpeg.yml'
      - 'internal/builder/**'
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: write

jobs:
  build:
    name: Build FFmpeg library for ${{ matrix.os }} ${{ matrix.arch }}
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - os: linux
            arch: amd64
            runner: ubuntu-24.04
          - os: linux
            arch: arm64
            runner: ubuntu-24.04-arm
          - os: darwin
            arch: amd64
            runner: macos-15-intel
          - os: darwin
            arch: arm64
            runner: macos-latest
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Show system info
        run: uname -a

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Install Linux dependencies
        if: matrix.os == 'linux'
        run: sudo apt-get update && sudo apt-get install -y yasm nasm meson gperf

      - name: Install macOS dependencies
        if: matrix.os == 'darwin'
        run: brew install yasm autoconf ragel meson nasm automake libtool

      - name: Create build directory
        run: mkdir -p build

      - name: Build FFmpeg library
        working-directory: build
        run: go run ../internal/builder/ ../libffmpeg_${{ matrix.os }}_${{ matrix.arch }}.a

      - name: List built files
        run: ls -la

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          title: "[CI] Rebuild ${{ matrix.os }} ${{ matrix.arch }} library"
          body: Automated changes by CI pipeline.
          commit-message: "[CI] Rebuild ${{ matrix.os }} ${{ matrix.arch }} library"
          committer: GitHub CI <noreply@github.com>
          author: GitHub CI <noreply@github.com>
          branch: ci/${{ matrix.os }}-${{ matrix.arch }}
          add-paths: libffmpeg_${{ matrix.os }}_${{ matrix.arch }}.a
